# KNN ALGORITHM

KNN - K Nearest Neighbors, is one of the simplest Supervised Machine Learning algorithm mostly used for.
It classifies a data point based on how its neighbors are classified.

k in KNN is a parameter that refers to the number of nearest neighbors to include in the majority voting process.
Generally k takes the value of sqrt(n), where 'n' is the total number of data points. And it's an odd number (impar).

For this Algorith we have tu use the Euclidean distance, which its formula is the distance between two points in the plane with coordenates (x,y) and (a,b) is:

$dist(d) = \sqrt{\left(x-a\right)^{2} + \left(y-b\right)^{2}}$

We have to calculate this distance for every point of the datset.

## USE CASE - Predict the specie of an Iris flower

<h3 style="color: blue">Import the required Scikit-Learn libraries as shown:

In [51]:
import pandas as pd   #Dataframes
import numpy as np    #Arrays of numbers

from sklearn.model_selection import train_test_split  #For spliting data 
from sklearn.preprocessing import StandardScaler      #Preprocesser
from sklearn.neighbors import KNeighborsClassifier    #The importan tool
from sklearn.metrics import confusion_matrix          #Test our model
from sklearn.metrics import f1_score                  #Test our model
from sklearn.metrics import accuracy_score            #Test our model

<h3 style="color:green">Load the dataset and have a look:</h3>

In [52]:
dataset = pd.read_csv('data/Iris_Data.csv')
print( len(dataset) )
print( dataset.head() )   #Only shows the first five lines

150
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [53]:
print(dataset)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12            4.8          3.0        

<h3 style="color: red;">Before proceeding further, let's split the dataset into train and test:</h3>

In [54]:
X = dataset.iloc[:,0:4]
y = dataset.iloc[:, 4]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.3)

<h3 style="color: purple;">Feature Scaling:</h3>

Any algorithm that computes distance or assumes normality, scale your features!

In [55]:
#Here we are gonna transform the data to be between -1 and 1
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#We never scale the "y" training or test.

<h3>Then define the model using KMeighborsClassifier and fit the train data in the model</h3>

In [56]:
import math
math.sqrt( len(y_pred) ) #This would be the value of "k", it has to be an odd number, remember.

6.708203932499369

In [57]:
#Define the model: Init K-NN
classifier = KNeighborsClassifier(n_neighbors=5, p=2, metric='euclidean')

In [58]:
#Fit Model
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [59]:
#Predict the test set results
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

<h3 style="color: green;">It's important to evaluate the model, let's use confusion matrix to do that</h3>

In [60]:
#Evaluate Model
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [61]:
print(accuracy_score(y_test, y_pred))

0.9777777777777777


Here we can see that our accuracy is 1.0, and it doesn't mean that our model is totally right, because no one is.
We have this kinda 'error' because our targe is a string type, and for this example we need a binary type (1 or 0).